package:
    name: mflow_nodes
    version: 0.0.1

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - mflow >=0.0.15
        - bottle
        - h5py
        - numpy
        - bitshuffle

about:
    summary: "Mflow nodes and their processors."
