package:
    name: mflow_nodes
    version: 0.0.1

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - mflow >=0.0.16
        - bitshuffle
        - bottle
        - h5py
        - numpy
        - requests


about:
    summary: "Mflow nodes and their processors."
